# Generated by Django 4.0.1 on 2022-02-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_uz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='subject_uz',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content_eng',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content_tr',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subject_en',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subject_tr',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
