# Generated by Django 4.0.1 on 2022-02-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_rename_name_category_name_uz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_eng',
            new_name='content_en',
        ),
    ]
